site_name: DIKU-jam

theme:
  name: material
  palette:
    - scheme: default
      primary: green
      accent: light green
  font:
    code: Comic Neue

nav:
  - Home: index.md
  - Rules: rules.md

copyright: The official DIKU-jam Game Jam
